### ISSUE TITLE
PostgreSQL credentials verstecken

### ISSUE THREAD

**Issue by nk027** [nk027/ineq_project#1]
Die credentials (bzw. das Passwort) für PostgreSQL sollten nicht auf GitHub öffentlich zugänglich sein und daher auch nicht in Scripts auftauchen. Das könnte man etwa mit einer Umgebungsvariable für das Passwort oder einem Script mit dem Passwort (im `.gitignore`) verhindern.

**Comment by nk027** [comment]
So wie es jetzt aussieht könnte man das `pg` Objekt ganz selbst in der Kommandozeile erstellen oder nur das Passwort händisch eingeben (wenn das sicher genug ist).

**Comment by nk027** [comment]
@stefanhumer 
Ich würde das in `_setup.R` so lösen:

`password <- readlines(prompt = "Please enter the PostgreSQL password:")`

`pg <- src_postgres(dbname = "dbname", host = "host", user = "user", password = password, options = "options")`

Also mit allen Infos außer dem Passwort im Code. Wäre das okay? (Alternativ auch mit [GetPass](https://cran.r-project.org/web/packages/getPass))

**Comment by mschnetzer** [comment]
Ich bin eben über das hier gestolpert: https://github.com/r-lib/keyring
Hat das Package mal jemand verwendet?

**Comment by nk027** [comment]
Sieht interessant aus!
Ist aber in dem Fall eher overkill, da die Zugangsdaten sowieso in den learn-Skripten schon als plaintext auftauchen.

Wenn jemand die Passwort-Eingabe umgehen will kann man sich [.Rprofile](https://www.statmethods.net/interface/customizing.html) ansehen.
