### ISSUE TITLE
Mögliche Ungleichheitsindikatoren

### ISSUE THREAD

**Issue by nk027** [nk027/ineq_project#2]
Klassische aus dem Assignment und Weiterführende.

**Comment by nk027** [comment]
[Discuss in Gdocs](https://docs.google.com/document/d/1Fr5YUrpIlhpfmtmO8X6gavAD0eZPVVwgrbQwp54gH0k/edit?usp=sharing)

**Comment by stefanhumer** [comment]
# Units of observation: 
a) individual: all individuals aged >=20 years
b) households: all households available in EU-SILC



# Income concepts:
**i) Pre-tax factor income (Canberra: primary income)**

  Sum of:
    (1) Income from employment (incl. self employed)
    (2) Property income
    (3) Income from household production

  Attention: (2+3) are household level variables, split them equally among household members >=20
  
  
**ii) Pre-tax national income (not equal to Canberra total income)**

  Sum of:
    (1)+(2)+(3)+
    (4) Pensions


**iii) Post-tax disposable income**

Sum of:
  (1)+(2)+(3)+(4)
  (5) all other monetary transfers recieved
  (6) minus all taxes and social security contributions

Again, split household level variables equally among household members aged >=20 years


# Time frame:
Sum of flows in one calender year
