### ISSUE TITLE
cross-sectional-data

### ISSUE THREAD

**Issue by Casputin** [nk027/ineq_project#3]
We need a way to make sure the right cross-sectional data is requested in _setup. 
Some variables are only available in certain years. For instance PL073 and PL074 etc., are only available in the c13p dataset: 
 `silc.p <- tbl(pg, "c13p") %>%
  filter(pb020 %in% country & pb010 %in% year) %>%
  select(pb020, pb030, pb040, pb150, py010g, px010, px030, pl060, pl073, pl074, pl100) %>%
  collect(n = Inf)`

**Comment by nk027** [comment]
In dem Fall würde ich es einfach möglichst allgemein gültig lassen. Wenn etwas spezielles gebraucht wird muss man halt selbst adaptieren.
