### ISSUE TITLE
Probleme soweit

### ISSUE THREAD

**Issue by nk027** [nk027/ineq_project#6]
Jemand...
- hat den `_template` Ordner gelöscht (am besten nochmal starten und den nicht löschen)
- hat das falsche `.Rproj` gelöscht (`ineq_project.Rproj` sollte bleiben)
- einige haben anscheinend in der Git Konfiguration eine andere Mail als auf GitHub (man taucht dann doppelt auf, siehe Git-Handout zur Konfiguration)
- hat `upstream` noch nicht hinzugefügt (siehe `README.Md`)
- hat nur geforked (oder noch nicht gepushed)

Und die beste Commit Message bis jetzt: "*change*"

**Comment by nk027** [comment]
Einige haben die Skripte aus dem `R` Ordner direkt in ihren eigenen kopiert - was natürlich möglich ist. Das macht allerdings nur Sinn, falls ihr die Skripte verändern wollt (also etwa für `_connection.R` nicht). Ansonsten könnt ihr die Skripte direkt sourcen (`source("R/_connection.R")`).

Side note: Ich hoffe, dass alle relative Pfade (d.h. das working directory des Projekts nicht verändern) verwenden.

**Comment by nk027** [comment]
- @LinoKK hat anscheinend vergessen auf UTF8 umzustellen ([siehe commit](https://github.com/LinoKK/ineq_project/commit/26eb81869344b58d55298330a79b8692fdc32151)) - das kann später einiges an Kopfschmerzen bereiten.

**Comment by LinoKK** [comment]
Moin,

bei mir steht da UTF8 wenn ich in R gehe:



Was hat das für Folgen? - Muss ich irgendwas machen?

**Comment by nk027** [comment]
@LinoKK In eurem Header (der Start von `GBR_template.Rmd`) hat es irgendwie die Sonderzeichen zusammengehaut (warum auch immer). Im besten Fall tauchen dann Sonderzeichen nicht auf, im schlimmsten Fall kann man das Dokument nicht mehr kompilieren (wäre hier wohl der Fall).

Wenn das mit UTF-8 passt würde ich einfach den Header nochmal entfernen und aus dem Template kopieren.

**Comment by LinoKK** [comment]
Ah okay. Das hatte ich gesehen, hatte das auch bei mir schon korrigiert aber eben erst gepusht.

**Comment by nk027** [comment]
@patrickzom & @jambon129 Wenn ihr das [so](https://github.com/Jambon129/ineq_project/blob/876f6073a47d3f8b2ba61f8a70db6ec81a8c0447/p1.R#L10) machen wollt könntet ihr es auf `password = password` ändern und euch in eurem `.Rprofile` die Variable erstellen ([siehe hier](https://www.statmethods.net/interface/customizing.html)). Das sollte weniger umständlich sein.

**Comment by MARGERITA2** [comment]
Darf ich dich bitten, das von mir hochgeladene File zu löschen. Damit, dass Passwort nicht sichtbar ist.

LG

Am 26.12.2018 um 12:49 schrieb Nikolas K. <notifications@github.com<mailto:notifications@github.com>>:


@patrickzom<https://github.com/patrickzom> & @Jambon129<https://github.com/Jambon129> Wenn ihr das so<https://github.com/Jambon129/ineq_project/blob/876f6073a47d3f8b2ba61f8a70db6ec81a8c0447/p1.R#L10> machen wollt könntet ihr es auf password = password ändern und euch in eurem .Rprofile die Variable erstellen (siehe hier<https://www.statmethods.net/interface/customizing.html>). Das sollte weniger umständlich sein.

@MARGERITA2<https://github.com/MARGERITA2> pls no<https://github.com/MARGERITA2/ineq_project/blob/f887ebc5391e5008dfcd3d55b1b5ef2448d7dc46/reports/ITA/Coding_Part_IT.R#L7>

**Comment by nk027** [comment]
> Darf ich dich bitten, das von mir hochgeladene File zu löschen. Damit, dass Passwort nicht sichtbar ist. LG

@MARGERITA2 Das ist eure Arbeit und ist wegen der Historie nicht ganz trivial - sprich [das](https://github.com/MARGERITA2/ineq_project/commit/9fb7806f542b7e9cf507d1592f3b8ca4ac611533) reicht nicht. Deswegen haben wir das auch extra oft wiederholt und dokumentiert.
Repository löschen und neu forken wäre eine Möglichkeit.

**Comment by Jambon129** [comment]
Hallo eine Frage:
Kann ich alles in knitR machen statt R-Markdown? Der Humer weiß das an und für sich eh, da ich das Projekt bei seinem R-und-LaTeX-Kurs auch als mein dortiges Kursprojekt angegeben hab, und er hat nichts dagegen gesagt. Aber gibt es ansonsten einen Grund anzunehmen dass das Problematisch sein könnte?

LG

**Comment by nk027** [comment]
@Jambon129 Meinst du direkt mit LaTeX?
Ich würde die Reports von der Seite aus nur als PDF anbieten, dann wäre das kein Problem. Mit Rmd kann man aber auch HTML Dokumente erstellen - wenn wir also unbedingt auch eigene Seiten wollen, wäre das leichter.
@mschnetzer @stefanhumer

**Comment by mschnetzer** [comment]
@Jambon129 Wir haben grundsätzlich keine Einwände, wenn die Seminararbeit mit knitR verfasst wird, v.a. wenn es Synergien mit anderen LVs gibt. Grundsätzlich empfehlen wir RMarkdown, weil es erstens einfacher als knitR ist und zweitens flexibler im Outputformat. Seminararbeit kann natürlich als PDF abgegeben werden (von Word raten wir hingegen eher ab).

**Comment by loremipsum007** [comment]
Hallo, ich habe einen merge conflict und kann ihn seit Stunden nicht lösen.
Es geht um ein Rmd und ein bibtex-file. Ich kann weder  committen noch pushen noch pullen. Ich habe versucht, einfach die Änderungen von meiner Kollegin zu übernehmen (in gitbash mit git checkout --theirs). Darauf bekomme ich weder eine Fehlermeldung noch eine "ok-Meldung". Wenn ich dann gitadd <filename>... tippe, schreibt er "nothing specified, nothing added" und die Konflikte sind noch immer da.
Wenn ich in RStudio auf diff klicke, ist das ganze File rot. Weiß nicht, ob und wie ich da noch was bearbeiten kann.
Wäre sehr danke für Hilfe! LG

**Comment by nk027** [comment]
@loremipsum007 Schwer zu sagen was da konkret das Problem ist.
Was kommen denn für Fehlermeldungen?

Wenn du's schnell & schmutzig erledigen willst:
- lokale Änderungen woanders speichern,
- lokales Repo löschen,
- remote Repo neu klonen,
- Änderungen wiederholen

**Comment by loremipsum007** [comment]
@nk027 danke für die schnelle Antwort!
Aber wie lösche ich mein lokales Repo? Hab gegooglet:
https://stackoverflow.com/questions/1514054/how-do-i-delete-a-local-repository-in-git
und bin so weit gekommen. Es ist aber laut dem letzten command noch was da. Also schließe ich daraus, dass es nicht gelöscht ist, oder? Und ich hab Windows.
![unbenannt](https://user-images.githubusercontent.com/44466536/50734099-8b861700-1199-11e9-9347-985997e3bb88.JPG)

**Comment by loremipsum007** [comment]
Und einfach den ganzen Projekt-Ordner löschen funktioniert nicht (Meldung: "Das Verzeichnis ist nicht leer")

**Comment by nk027** [comment]
Also am Screenshot sieht es so aus als wäre das Repo (i.e. alles in `.git`) weg. Das könnte man jetzt neu verknüpfen, ich würde aber den ganzen Ordner löschen oder zumindest alles neu klonen.

Für die Meldung hab ich mal [das](https://www.repairwin.com/fix-cannot-remove-folder-directory-is-not-empty-solved/) gefunden.

**Comment by mschnetzer** [comment]
@loremipsum007 Bin am Donnerstag an der WU und kann am Nachmittag bei Bedarf eine "Sprechstunde" mit Troubleshooting machen. Kurz nach 14 Uhr bin ich verfügbar.

**Comment by loremipsum007** [comment]
@nk027 danke für die Unterstützung!
@mschnetzer, danke, ein kurzes Troubleshooting am Donnerstag wäre toll (wie meine Kollegin Martina Pardy bereits im Mail mit dem html-Dokument erwähnt hat)
