### ISSUE TITLE
Pshing into /R folder

### ISSUE THREAD

**Issue by lasserro** [nk027/ineq_project#8]
Hab ein Skript (_setup_including_py021g.R) in den /R folder hinzugefügt, commited und gepushed. bin mir nur nicht sicher ob das jetzt nur in unserer fork geändert wurde oder nicht.

**Comment by Casputin** [comment]
It was only added to your Fork.

**Comment by lasserro** [comment]
could someone with push access include it globally?

**Comment by Casputin** [comment]
That would probably mean that we would have to check your script. Since your Fork is public, our colleagues can access it if they want to.

**Comment by lasserro** [comment]
i already checked with mr. humer. its okay

**Comment by nk027** [comment]
Thanks for sharing!
If it works in general you can open a pull request and someone with write-access (e.g. @stefanhumer) can test it and merge your changes.
I've included the crucial part (7ff8c4d81135f7bbf90369ad9c289ceee7159ef0) as a template; someone might want to try your approach.
